# Generated by Django 5.2.1 on 2025-05-27 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_pedido_delete_dados_produto_categoria_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='preco',
        ),
    ]
